#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define GOOGLE_CALENDAR_ID "YOUR_GOOGLE_CALENDAR_ID"
#define GOOGLE_CLIENT_ID "YOUR_GOOGLE_CLIENT_ID"
#define GOOGLE_CLIENT_SECRET "YOUR_GOOGLE_CLIENT_SECRET"
#define GOOGLE_REFRESH_TOKEN "YOUR_GOOGLE_REFRESH_TOKEN"
#define GOOGLE_REFRESH_TOKEN_PAYLOAD "client_id=" GOOGLE_CLIENT_ID "&client_secret=" GOOGLE_CLIENT_SECRET "&grant_type=refresh_token&refresh_token=" GOOGLE_REFRESH_TOKEN

#define API_WEATHER_API_KEY "YOUR_API_WEATHER_API_KEY"
#define API_WEATHER_GEOCODE "XX.XX,YY.YY" // Latitude, Longitude
#define API_WEATHER_FORECAST_URL "https://api.weather.com/v3/wx/forecast/daily/5day?geocode=" API_WEATHER_GEOCODE "&format=json&units=m&language=de-DE&apiKey=" API_WEATHER_API_KEY
#define WEATHER_STATION_ID "YOUR_STATION_ID"
#define API_WEATHER_URL "https://api.weather.com/v2/pws/observations/current?stationId=" WEATHER_STATION_ID "&format=json&units=m&apiKey=" API_WEATHER_API_KEY

#define FITX_STUDIO_NAME_1 "YOUR_STUDIO_NAME_1"
#define FITX_STUDIO_NAME_2 "YOUR_STUDIO_NAME_2"
#define FITX_STUDIO_ID_1 1234567890
#define FITX_STUDIO_ID_2 9876543210

#define URL_BAHN_1 "YOUR_TRANSPORT_SERVICE_URL_1"
#define URL_BAHN_2 "YOUR_TRANSPORT_SERVICE_URL_2"
#define URL_BAHN_3 "YOUR_TRANSPORT_SERVICE_URL_3"

#define BAHN_1 "YOUR_ROUTE_DIRECTION_1"
#define BAHN_2 "YOUR_ROUTE_DIRECTION_2"
#define BAHN_3 "YOUR_ROUTE_DIRECTION_3"
